@baseUrl = http://localhost:3333

# @name Create_user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "name":"Richard Lirio",
    "email": "richard@hotmail.com",
    "password": "123456"
}

###


# @name Fetch_all_users
GET {{baseUrl}}/api/users
Content-Type: application/json

###